name: CI
on:
  push:
    branches:
      - master

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: 'windows'
          - os: ubuntu-latest
            preset: 'unix'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set C++/C compiler on macOS
        shell: bash
        run: echo "CC=gcc-11" >> $GITHUB_ENV; echo "CXX=g++-11" >> $GITHUB_ENV;
        if: runner.os == 'macOS'

      - name: Set C++ VCPKG_ROOT
        shell: bash
        run: echo VCPKG_ROOT="$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"; cat "$GITHUB_ENV"

      - name: Tool versions
        shell: bash
        run: |
          g++ --version
          make --version
        if: runner.os == 'Linux' || runner.os == 'macOS'

      - name: Install system dependencies
        # Some is needed by SDL3
        run: sudo apt-get update && sudo apt-get install -y libltdl-dev libx11-dev libxft-dev libxext-dev libxext-dev autoconf autoconf-archive automake libtool
        if: runner.os == 'Linux'

      - name: Test ports
        shell: bash
        run: python test_ports.py --preset=${{ matrix.preset }}
